services:

  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    depends_on:
      - mongo
    ports:
      - "80:80"
      - "2333:2333" # console
      - "2345:2345" # debug

    environment:
      EASTLAUGH_TOKEN_PWD: ${EASTLAUGH_TOKEN_PWD}
      DEEPSEEK_API_KEY: ${DEEPSEEK_API_KEY}
      EASTLAUGH_MONGODB_URI: mongodb://mongo:27017/webapp
      EASTLAUGH_ADDR: :80
      EASTLAUGH_CONSOLE_ADDR: :2333
      QWEN_API_KEY: ${QWEN_API_KEY}
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH: false
