services:
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    depends_on:
      - mongo
    ports:
      - "80:80"
      - "2333:2333" # console
      - "2345:2345" # dlv

    environment:
      EASTLAUGH_TOKEN_PWD: ${EASTLAUGH_TOKEN_PWD}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_BASE_URL: ${OPENAI_BASE_URL}
      OPENAI_MODEL: ${OPENAI_MODEL}
      OPENAI_EMBEDDING_MODEL: ${OPENAI_EMBEDDING_MODEL}
      EASTLAUGH_CONSOLE_ADDR: ${EASTLAUGH_CONSOLE_ADDR}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      
      EASTLAUGH_MONGODB_URI: mongodb://mongo:27017/webapp
      EASTLAUGH_ADDR: :80
  mongo:
    image: mongo
    ports:
      - "27017:27017"

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_BASICAUTH: false
