// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"
	"time"

	"github.com/gin-gonic/gin"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes = "BearerAuth.Scopes"
)

// ServerUrl defines the Server URL for 本地开发服务器
const ServerUrl = "http://localhost:8080/api/v1"

// Defines values for ChatRequestMessagesRole.
const (
	Assistant ChatRequestMessagesRole = "assistant"
	System    ChatRequestMessagesRole = "system"
	User      ChatRequestMessagesRole = "user"
)

// AuthRequest defines model for AuthRequest.
type AuthRequest struct {
	// Code 验证码
	Code string `json:"code"`

	// Email 邮箱
	Email openapi_types.Email `json:"email"`
}

// AuthResponse defines model for AuthResponse.
type AuthResponse struct {
	// Token 认证令牌
	Token *string `json:"token,omitempty"`
}

// ChatRequest defines model for ChatRequest.
type ChatRequest struct {
	// Messages 对话消息列表
	Messages []struct {
		// Content 消息内容
		Content string `json:"content"`

		// Role 消息角色
		Role ChatRequestMessagesRole `json:"role"`
	} `json:"messages"`
}

// ChatRequestMessagesRole 消息角色
type ChatRequestMessagesRole string

// CreatePostRequest defines model for CreatePostRequest.
type CreatePostRequest struct {
	// Content 评论内容
	Content string `json:"content"`

	// File 博客文件名
	File string `json:"file"`
}

// Post defines model for Post.
type Post struct {
	// Content 评论内容
	Content *string `json:"content,omitempty"`

	// CreatedAt 创建时间
	CreatedAt *time.Time `json:"created_at,omitempty"`

	// Email 邮箱
	Email *openapi_types.Email `json:"email,omitempty"`

	// File 博客文件名
	File *string `json:"file,omitempty"`
	Id   *int    `json:"id,omitempty"`
}

// GetPostsParams defines parameters for GetPosts.
type GetPostsParams struct {
	// File 博客文件名，如 post.md
	File string `form:"file" json:"file"`
}

// PostAuthJSONRequestBody defines body for PostAuth for application/json ContentType.
type PostAuthJSONRequestBody = AuthRequest

// PostChatJSONRequestBody defines body for PostChat for application/json ContentType.
type PostChatJSONRequestBody = ChatRequest

// PostPostsJSONRequestBody defines body for PostPosts for application/json ContentType.
type PostPostsJSONRequestBody = CreatePostRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// 邮箱验证码认证
	// (POST /auth)
	PostAuth(c *gin.Context)
	// 聊天对话
	// (POST /chat)
	PostChat(c *gin.Context)
	// 获取评论列表
	// (GET /posts)
	GetPosts(c *gin.Context, params GetPostsParams)
	// 创建评论
	// (POST /posts)
	PostPosts(c *gin.Context)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandler       func(*gin.Context, error, int)
}

type MiddlewareFunc func(c *gin.Context)

// PostAuth operation middleware
func (siw *ServerInterfaceWrapper) PostAuth(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostAuth(c)
}

// PostChat operation middleware
func (siw *ServerInterfaceWrapper) PostChat(c *gin.Context) {

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostChat(c)
}

// GetPosts operation middleware
func (siw *ServerInterfaceWrapper) GetPosts(c *gin.Context) {

	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetPostsParams

	// ------------- Required query parameter "file" -------------

	if paramValue := c.Query("file"); paramValue != "" {

	} else {
		siw.ErrorHandler(c, fmt.Errorf("Query argument file is required, but not found"), http.StatusBadRequest)
		return
	}

	err = runtime.BindQueryParameter("form", true, true, "file", c.Request.URL.Query(), &params.File)
	if err != nil {
		siw.ErrorHandler(c, fmt.Errorf("Invalid format for parameter file: %w", err), http.StatusBadRequest)
		return
	}

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.GetPosts(c, params)
}

// PostPosts operation middleware
func (siw *ServerInterfaceWrapper) PostPosts(c *gin.Context) {

	c.Set(BearerAuthScopes, []string{})

	for _, middleware := range siw.HandlerMiddlewares {
		middleware(c)
		if c.IsAborted() {
			return
		}
	}

	siw.Handler.PostPosts(c)
}

// GinServerOptions provides options for the Gin server.
type GinServerOptions struct {
	BaseURL      string
	Middlewares  []MiddlewareFunc
	ErrorHandler func(*gin.Context, error, int)
}

// RegisterHandlers creates http.Handler with routing matching OpenAPI spec.
func RegisterHandlers(router gin.IRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, GinServerOptions{})
}

// RegisterHandlersWithOptions creates http.Handler with additional options
func RegisterHandlersWithOptions(router gin.IRouter, si ServerInterface, options GinServerOptions) {
	errorHandler := options.ErrorHandler
	if errorHandler == nil {
		errorHandler = func(c *gin.Context, err error, statusCode int) {
			c.JSON(statusCode, gin.H{"msg": err.Error()})
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandler:       errorHandler,
	}

	router.POST(options.BaseURL+"/auth", wrapper.PostAuth)
	router.POST(options.BaseURL+"/chat", wrapper.PostChat)
	router.GET(options.BaseURL+"/posts", wrapper.GetPosts)
	router.POST(options.BaseURL+"/posts", wrapper.PostPosts)
}
