services:
  mysql:
    image: mysql:8.0
    container_name: webapp-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: webapp
    ports:
      - "3307:3306"
#     volumes:
#       - mysql_data:/var/lib/mysql

# volumes:
#   mysql_data:

# docker run -d --name webapp-mysql -e MYSQL_ALLOW_EMPTY_PASSWORD=yes -e MYSQL_DATABASE=webapp -p 3307:3306 mysql:8.0