name: Makefile CI

on:
  workflow_dispatch:
    
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: 生成单文件可执行程序
      run: make server_binary
